/*
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/*
 * This file contains definitions of Balance Mod resources, much
 * like the other headers included from resinst.h (although this
 * is not autogenerated).
 */

#ifndef BALANCE_RES_H
#define BALANCE_RES_H

/* Strings */
#define BALANCE_STRINGS "text.balance_strings"

/* Graphics */
#define RETICLE_BIG_MASK_PMAP_ANIM "graphics.reticle.large"
#define RETICLE_MED_MASK_PMAP_ANIM "graphics.reticle.medium"
#define RETICLE_SML_MASK_PMAP_ANIM "graphics.reticle.small"
#define RETREAT_SLASH_MASK_PMAP_ANIM "graphics.retreat_reticle"

#endif /* BALANCE_RES_H */
